import React, { useEffect, useRef, useState } from "react";
import { Button, IconButton, TextField } from "@mui/material";
import io from "socket.io-client";
import VideoChat from "../components/VideoChat";
import Head from 'next/head';
import styles from '/styles/Home.module.css';

const socket = io.connect('/', { transports : ['websocket'] });

export default function Home() {
  const [userName, setUserName] = useState("");
  const [userId, setUserId] = useState("");
  const [isReady, setIsReady] = useState(false);
  const [errMsg, setErrMsg] = useState("");

  useEffect(() => {
    socket.on("userId", (id) => {
      setUserId(id);
    });

    return () => {
      socket.off("user");
    }
  }, []);

  const openVideChat = () => {
    socket.emit("addUser", { name: userName, id: userId }, (err, msg) => {
      if (err) return setErrMsg(msg);
      setErrMsg("");
      setIsReady(true);
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Video Chat webRTC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {userId &&
      (<main className={styles.mainContainer}>
        {!isReady && (<h1 style={{ textAlign: "center", color: '#fff' }}>Video Chat App</h1>)}
        {!isReady ?
        (
          <div className={styles.inputContainer}>
            {errMsg && (<h6 style={{ textAlign: "center", color: 'red', marginTop: "-10px", marginBottom: "10px", }}>{errMsg}</h6>)}
            <TextField
              id="filled-basic"
              label="Name"
              variant="filled"
              value={userName}
              onChange={(e) => setUserName(e.target.value)}
              style={{ marginBottom: "20px" }}
              />
            <Button disabled={userName === ""} variant="contained" color="primary" onClick={() => openVideChat()}>Enter Video Chat</Button>
          </div>
        )
        :
        (<VideoChat userName={userName} userId={userId} setUserId={setUserId} socket={socket} />)}
      </main>)}
    </div>
  )
}